# Generated by Django 4.0.2 on 2022-03-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('basicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuedBooks', to='basicApp.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuingUser', to='accounts.user')),
            ],
        ),
    ]
