# Generated by Django 4.0.2 on 2022-03-06 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicApp', '0005_remove_issuedbooks_name_alter_issuedbooks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbooks',
            name='book',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='issuedBooks', to='basicApp.books'),
        ),
        migrations.AlterField(
            model_name='issuedbooks',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
